# -*- coding: utf-8 -*-
"""(제출) kluebert_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vjap3SoCu0Y7fuQ8uepemhdA4FYg03F
"""

disease = "depression"  # addiction, depression, anxiety 중 택 1

import torch
import numpy as np
import pandas as pd
from transformers import BertTokenizer, BertForSequenceClassification
import os
import json


# 데이터셋 토큰화 함수 정의
# def tokenize_function(examples):
#     return tokenizer(examples['input'], padding='max_length', truncation=True)

def get_analysis_summary(final_level):
    summary_map = {
        0: "정상 범위 내의 정서 상태",
        1: "경미한 우울 증상 의심",
        2: "중간 수준의 우울 증상 의심",
        3: "심화된 우울 증상 의심"
    }
    return summary_map.get(final_level, "분석 결과 없음")


# [수정/추가된 부분] 분류 모델(Softmax) 기반의 확률 계산 및 DB 컬렉션 구조에 맞춘 출력 포맷 적용
def predict(sentence, model, tokenizer):
    inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True, max_length=512)
    inputs = {k: v.to(device) for k, v in inputs.items()}  # GPU로 이동
    model.to(device)  # 모델을 GPU로 이동
    with torch.no_grad():
        outputs = model(**inputs)

    probs = torch.softmax(outputs.logits, dim=-1).squeeze()
    dep_lvl = int(torch.argmax(probs).item())
    raw_score = float(sum(i * prob for i, prob in enumerate(probs)))

    result = {
        "ANALYSIS_SUM": get_analysis_summary(dep_lvl),
        "DEP_RES": {
            "DISEASE_TYPE": disease,
            "DEP_LVL": int(dep_lvl),
            "DEP_SCORE": round(raw_score, 2),
            "IS_SYMPTOM": bool(dep_lvl != 0)
        }
    }
    return result


# TEST SET 폴더 입장
folder_path = './data/test'  # 폴더 내 test 데이터셋이 있는 경로 설정

# [수정/추가된 부분] 불안, 중독 등 타 질환 파일도 모두 테스트에 포함하여 변별력 평가
test_json_files = [f for f in os.listdir(folder_path) if f.endswith('.json')]

# JSON 파일 하나씩 열어서 데이터 가져오기
test_labels = []
test_txts = []
valid_test_json_files = []

for json_file in test_json_files:
    file_path = os.path.join(folder_path, json_file)

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            js = json.load(f)

            # [수정/추가된 부분] null 처리 및 정수 변환 안전장치
            label_val = js.get(disease, 0)
            if label_val is None: label_val = 0
            test_labels.append(int(label_val))

            paragraghs = js.get("paragraph", [])

            sentences = ""
            for token in paragraghs:
                speaker = token.get("paragraph_speaker", "")
                text = token.get("paragraph_text", "")

                # 문장 생성 (스피커와 텍스트를 합쳐서 저장)
                token_sentence = f"{speaker}: {text}\n"
                sentences += token_sentence  # 문장을 계속해서 더함

            test_txts.append(sentences)
            valid_test_json_files.append(json_file)
    except Exception:
        continue

test_json_files = valid_test_json_files

if __name__ == "__main__":

    # GPU 또는 CPU 장치 설정
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # [수정/추가된 부분] Custom 클래스 대신 기본 BertForSequenceClassification 사용
    loaded_model = BertForSequenceClassification.from_pretrained("./trained_model_kluebert_" + disease).to(device)
    loaded_tokenizer = BertTokenizer.from_pretrained("./trained_model_kluebert_" + disease)

    loaded_model.eval()

    # 예측 예시 (로드된 모델을 사용),  test_sentence 에는 임의의 텍스트들을 편집 가능하게 넣고 테스트해보실 수 있습니다.
    test_sentence = "오늘은 평소보다 알람 소리가 조금 더 가깝게 들리는 아침이었다. 몸이 천근만근이었지만 겨우 일어나 기지개를 켜고 하루를 시작했다.점심에는 뭘 먹을까 고민하다가 근처 식당에서 늘 먹던 메뉴를 골랐다. 아는 맛이 무섭다더니, 역시 실패 없는 선택이었다. 식후에 마신 시원한 아이스 아메리카노 한 잔이 오늘 하루 중 가장 큰 활력소였던 것 같다.오후에는 밀린 일들을 하나씩 처리했다. 중간에 조금 지치기도 했지만, 창밖으로 들어오는 햇살이 나쁘지 않아 견딜만했다. 퇴근길에는 좋아하는 노래 플레이리스트를 들으며 걸었는데, 가사 하나하나가 평소보다 더 귀에 잘 들어오는 기분이었다.집에 돌아와 씻고 누우니 이제야 진정한 휴식이라는 느낌이 든다. 거창한 이벤트는 없었지만, 큰 사고 없이 무사히 하루를 마쳤다는 사실만으로도 충분히 감사한 일이다. 내일도 오늘만 같았으면 좋겠다."  # 테스트할 문장 입력
    dep_res = predict(test_sentence, loaded_model, loaded_tokenizer)
    print(f"\nInput: {test_sentence}\nDepression Result: {dep_res}")

    assert len(test_labels) == len(test_txts)

    test_df = pd.DataFrame({
        'filename': test_json_files,
        'input': test_txts,
        'original_label': test_labels,
        'original_label_zeroone': [0 if x == 0 else 1 for x in test_labels]
    })

    # 예측 결과를 담을 리스트
    predicted_labels = []
    predicted_raw_scores = []
    predicted_is_symptom = []
    predicted_analysis_summary = []

    # 각 문장에 대해 예측 수행
    for sentence in test_df['input']:
        dep_res = predict(sentence, loaded_model, loaded_tokenizer)
        # [수정/추가된 부분] DB 스키마 구조(DEP_RES)에 맞춰서 값 추출하도록 변경
        predicted_labels.append(dep_res['DEP_RES']['DEP_LVL'])
        predicted_raw_scores.append(dep_res['DEP_RES']['DEP_SCORE'])
        predicted_is_symptom.append(dep_res['DEP_RES']['IS_SYMPTOM'])
        predicted_analysis_summary.append(dep_res['ANALYSIS_SUM'])

    # 예측 결과를 새로운 컬럼 'predicted_label'에 추가
    test_df['predicted_label'] = predicted_labels
    test_df['predicted_raw_score'] = predicted_raw_scores
    test_df['predicted_is_symptom'] = predicted_is_symptom
    test_df['predicted_analysis_summary'] = predicted_analysis_summary
    test_df['predicted_label_zeroone'] = [0 if x == 0 else 1 for x in predicted_labels]

    # numpy 배열로 변환 (계산을 쉽게 하기 위해)
    original_label_zeroone = np.array(test_df['original_label_zeroone'])
    predicted_label_zeroone = np.array(test_df['predicted_label_zeroone'])

    # 정확도 계산: 예측이 정확한 경우의 수 / 전체 데이터 수
    accuracy_zeroone = np.mean(original_label_zeroone == predicted_label_zeroone)

    # 정확도 출력
    print(disease, "0~1")
    print(f"Accuracy: {accuracy_zeroone * 100:.2f}%")